- wp-content/themes/cambodia-ict-camp/functions.php
- wp-content/themes/cambodia-ict-camp/inc/taxonomy-form-fields/categories/colors.php
Add color picker on Theme (category) Management
> [TASK] Add color picker on theme

- wp-content/themes/cambodia-ict-camp/archive-speakers.php
- wp-content/themes/cambodia-ict-camp/functions.php
- wp-content/themes/cambodia-ict-camp/inc/custom-meta-boxes/speakers/expertise.php
- wp-content/themes/cambodia-ict-camp/inc/custom-meta-boxes/speakers/organization.php
- wp-content/themes/cambodia-ict-camp/inc/custom-meta-boxes/speakers/social-media-links.php
- Link speaker's name to his or her LinkedIn instead of LinkedIn icon.
- Add Speaker's organization name.
> [TASK] Update Speaker Bio page

- wp-content/themes/cambodia-ict-camp/style.css
Change footer menu item color.
> [IMP] Improve styling on footer menu

- wp-content/themes/cambodia-ict-camp/functions.php
- wp-content/themes/cambodia-ict-camp/hooks/feature-info.php
- wp-content/themes/cambodia-ict-camp/style.css
- wp-content/themes/event-star/acmethemes/customizer/feature-section/feature-info.php
To get the date format for the countdown feature box, I decided to make the direct change on the Parent Theme.
This is a quick solution for now, but I am still looking for a better way to customize the parent theme without making the direct changes to the original code of the parent theme.
Partially fixed: #15
> [TASK] Add countdown to feature info box

- wp-content/themes/cambodia-ict-camp/archive-speakers.php
- wp-content/themes/cambodia-ict-camp/inc/template-tags.php
- wp-content/themes/cambodia-ict-camp/index.php
> [TASK] Change Post page title to "Blog"

- wp-content/themes/cambodia-ict-camp/page-about.php
- wp-content/themes/cambodia-ict-camp/style.css
> [IMP] Improve display on About Page

- wp-content/themes/cambodia-ict-camp/header.php
- wp-content/themes/cambodia-ict-camp/style.css
Set different font-family for the content of the site in different languages.
> [TASK] Set different font for different language

- wp-content/themes/cambodia-ict-camp/widgets/camp-posts-no-img.php
`$instance['title']` appear to be the only attribute that work with qTranslation.
Therefore, I basically changed `$instance['event-star-widget-title']` to `$instance['title']`
> [BUGFIX] Fix not translated Post Widget Title

- wp-content/themes/cambodia-ict-camp/functions.php
- wp-content/themes/cambodia-ict-camp/header.php
- wp-content/themes/cambodia-ict-camp/hooks/header.php
- wp-content/themes/cambodia-ict-camp/inc/localize-manager.php
- wp-content/themes/cambodia-ict-camp/style.css
> [TASK] Move Language Switcher to Top Menu

- wp-content/themes/cambodia-ict-camp/inc/custom-taxonomies/years.php
> [TASK] Change `Year` to `Year of Camp`

- wp-content/themes/cambodia-ict-camp/archive-facilitators.php
- wp-content/themes/cambodia-ict-camp/page-about.php
- wp-content/themes/cambodia-ict-camp/style.css
Add styling to center the grid list of bootstrap.
> [TASK] Centering the list grid

- wp-content/themes/cambodia-ict-camp/inc/template-parts/facilitators/content-list.php
> [IMP] Increase side of modal dialogue

- wp-content/themes/cambodia-ict-camp/style.css
> [IMP] Fix error grid list on Small Screen view

- wp-content/themes/cambodia-ict-camp/functions.php
- wp-content/themes/cambodia-ict-camp/style.css
> [TASK] Change Khmer Font

- wp-content/themes/cambodia-ict-camp/style.css
In this issue, I implement with Hex code color and opacity.
Resource: https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4
> [TASK] Change button color on mouse hover

- wp-content/themes/cambodia-ict-camp/style.css
> [TASK] Decrease font size on p and li for Khmer

- wp-content/themes/cambodia-ict-camp/archive-facilitators.php
- wp-content/themes/cambodia-ict-camp/inc/template-parts/facilitators/content-list.php
> [TASK] Increase number of facilitator in one row

- wp-content/themes/cambodia-ict-camp/archive-facilitators.php
- wp-content/themes/cambodia-ict-camp/style.css
Apply clean code and improve on Facilitator Archive page.
> [IMP] Improve archive-facilitator and code clean

- wp-content/themes/cambodia-ict-camp/style.css
Change HEX code color HEX with the transparent to rgba() due to the reason that code color HEX with the transparent does not support for all browser including IE.
> [IMP] Update color code HEX to rgba

- wp-content/themes/cambodia-ict-camp/style.css
- Clean code on spacing
- Change hover color of <a> on top nav
> [IMP] Change hover color of <a> on top nav

- wp-content/themes/cambodia-ict-camp/template-simple-agenda.php
This code implementation help fixed the scrolling error of Tab view (issue #108). However, it leads to a small change: There is no hash anymore when clicking on different tabs. Example: `cambodiaict.net/agenda#day2`
> [BUGFIX] Prevent scrolling when click on tab

- wp-content/themes/cambodia-ict-camp/archive-facilitators.php
- wp-content/themes/cambodia-ict-camp/archive-speakers.php
> [BUGFIX] Fix view & sort speakers and facilitators

- wp-content/themes/cambodia-ict-camp/archive-speakers.php
- wp-content/themes/cambodia-ict-camp/style.css
> [IMP] Remove border from info-box widget

- wp-content/themes/cambodia-ict-camp/archive-facilitators.php
> [IMP] Reorder Facilitator page sections

- wp-content/themes/cambodia-ict-camp/archive-speakers.php
- wp-content/themes/cambodia-ict-camp/inc/template-parts/facilitators/content-list.php
- wp-content/themes/cambodia-ict-camp/inc/template-parts/speakers/content-list.php
>  [IMP] Show 3 items/row on facilitator and speaker

- wp-content/themes/cambodia-ict-camp/style.css
> [IMP] Add paper stack style on photo album cover

- wp-content/themes/cambodia-ict-camp/hooks/slider-selection.php
- wp-content/themes/cambodia-ict-camp/style.css
According to SEO guideline, add the `<h1>` tag is missing on the Homepage of the website.
Fixed issue #181
> [IMP] Add <h1> to banner-title on Homepage

- wp-content/themes/cambodia-ict-camp/functions.php
- wp-content/themes/cambodia-ict-camp/inc/custom-post-types/slide-presentations.php
- wp-content/themes/cambodia-ict-camp/style.css
- wp-content/themes/cambodia-ict-camp/template-highlight.php
Display Slide presentation with thumbnail.
The entire page:
> [TASK] Implement Slide presentation display on Resource page

- wp-content/themes/cambodia-ict-camp/inc/custom-post-types/announcements.php
- wp-content/themes/cambodia-ict-camp/inc/custom-post-types/donors.php
- wp-content/themes/cambodia-ict-camp/inc/custom-post-types/facilitators.php
- wp-content/themes/cambodia-ict-camp/inc/custom-post-types/organizers.php
- wp-content/themes/cambodia-ict-camp/inc/custom-post-types/partners.php
- wp-content/themes/cambodia-ict-camp/inc/custom-post-types/sessions.php
- wp-content/themes/cambodia-ict-camp/inc/custom-post-types/speakers.php
- Add `camp_year` taxonomy to speakers
- Update custom taxonomy name `year` to `camp_year`
> [TASK] Add camp_year taxonomy to Speaker post type

- wp-content/themes/cambodia-ict-camp/inc/shortcode/display-custom-post-type.php
> [IMP] Remove <div class="container"> ... </div> from $post_list

- wp-content/themes/cambodia-ict-camp/index.php
> [IMP] Enhance UI of Carousel with few image

- wp-content/themes/cambodia-ict-camp/index.php
- wp-content/themes/cambodia-ict-camp/style.css
> [TASK] Limit the maximum number of carousel dots to 4

- wp-content/themes/cambodia-ict-camp/archive.php
> [TASK] Update Tag page to be consistent with blog page

- wp-content/themes/cambodia-ict-camp/inc/shortcode/display-custom-post-type.php
> [IMP] Enhance shortcode for displaying post type

- wp-content/themes/cambodia-ict-camp/functions.php
- wp-content/themes/cambodia-ict-camp/hooks/excerpts.php
> [TASK] Enhance excerpt trim on Khmer Language

- wp-content/themes/cambodia-ict-camp/inc/template-parts/blogs/carousel.php
- wp-content/themes/cambodia-ict-camp/index.php
Fixed issue #217 
Rather than commenting on the carousel/slider section, I decided to add a switch for turning it on and off.
> [TASK] Adding switch for carousel on Blog page

- wp-content/themes/cambodia-ict-camp/template-speaker-list.php
Create a new template for archiving speakers by year on different pages.
> [TASK] Create template to archive speakers by year

- wp-content/themes/cambodia-ict-camp/template-facilitator-list.php
Create a new template for the facilitator list to display by year of the camp.
> [TASK] Create template for archiving facilitator list

- wp-content/themes/cambodia-ict-camp/template-presentation-list.php
Create a new template to display the Slide presentation by year of the camp.
> [TASK] Create template to archive slide presentation by year
